---
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

clientId: "client-id.apps.googleusercontent.com"
clientSecret: "mfhdsfgdshfguy47862437264832"
scopes:
  - "https://www.googleapis.com/auth/contacts"
redirectionURL: "http://localhost:8080/auth/redirect/code"